9.58+ds-3 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/udev-scripts/hdparm b/debian/udev-scripts/hdparm
--- a/debian/udev-scripts/hdparm
+++ b/debian/udev-scripts/hdparm
@@ -7,27 +7,44 @@ set -e
 . /lib/hdparm/hdparm-functions
 
 if [ -e /proc/cmdline ]; then #linux only - future proofing against BSD and Hurd :)
-	if grep -wq nohdparm /proc/cmdline ; then
-		exit 0
-	fi
+        if grep -wq nohdparm /proc/cmdline ; then
+                exit 0
+        fi
 fi
 
 raidstat=OK
 if [ -e /proc/mdstat ]; then
-	if egrep -iq "resync|repair|recover|check" /proc/mdstat; then
-		raidstat=RESYNC
-	fi
+        if egrep -iq "resync|repair|recover|check" /proc/mdstat; then
+                raidstat=RESYNC
+        fi
 elif [ -e /proc/rd/status ]; then
-	raidstat=`cat /proc/rd/status`
+        raidstat=`cat /proc/rd/status`
 fi
 
 if ! [ "$raidstat" = 'OK' ]; then
-	exit 1
+        exit 1
 fi
 
-OPTIONS=$(hdparm_options $DEVNAME)
+die() { echo "$*" 1>&2 ; exit 1; }
+OPTIONS=$(hdparm_options $DEVNAME) || die "hdparm_options failed with: $OPTIONS"
+apmopts=''
 if [ -n "$OPTIONS" ]; then
-	/sbin/hdparm $OPTIONS $DEVNAME 2>/dev/null
+        for opt in $OPTIONS; do
+                case $opt in
+                        (*'-B'*|*'-S'*|*'force_spindown_time'*)
+                                apmopts='true'
+                        ;;
+                esac
+        done
+        if [ "$apmopts" = true ]; then
+                /usr/lib/pm-utils/power.d/95hdparm-apm resume
+        fi
+        # strip -S (spindown) and -B (apm), force_spindown_time, -q and empty white spaces
+        # apm options are handled by /usr/lib/pm-utils/power.d/95hdparm-apm
+        OPTIONS=$(echo $OPTIONS | perl -pe 's/((-S|-B|force_spindown_time)[\d]{1,3})|(-q\s?)|(\s?)//g')
+        if [ -n "$OPTIONS" ]; then
+                /sbin/hdparm -q $OPTIONS $DEVNAME 2>/dev/null
+        fi
 fi
 
 exit 0
